# This file shows the format for secrets in Streamlit Cloud
# DO NOT commit this file with real secrets
# Add your actual API key in Streamlit Cloud Settings -> Secrets

# OPENAI_API_KEY = "your-api-key-here"